### ISSUE TITLE
Compilation Error ffmpeg library not found

### ISSUE THREAD

**Issue by saeschdivara** [meh/rust-ffmpeg#48]
Hi

I work with Ubuntu 14.04 64bit and rustc 1.4.0-dev
I have the following error:

   Compiling ffmpeg-sys v2.8.0-5
   Compiling bitflags v0.3.2
   Compiling libc v0.2.2
   Compiling ffmpeg v0.1.1 (https://github.com/meh/rust-ffmpeg#67009f0f)
   Compiling myserver v0.1.0 (file:///home/saskyrar/Development/Languages/rust/myserver)
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/myserver.0.o" "-o" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/myserver" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/deps/libffmpeg-2237698f5e29be22.rlib" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/deps/libffmpeg_sys-72b52694e5f2edc4.rlib" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/deps/liblibc-540159808ccfa9ab.rlib" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/deps/libbitflags-c495827ddcd6a202.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-a5fc0d6c.rlib" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-a5fc0d6c.rlib" "-L" "/home/saskyrar/Development/Languages/rust/myserver/target/debug" "-L" "/home/saskyrar/Development/Languages/rust/myserver/target/debug/deps" "-L" "/usr/lib/rust/rust-stable/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/saskyrar/Development/Languages/rust/myserver/.rust/lib/x86_64-unknown-linux-gnu" "-L" "/home/saskyrar/Development/Languages/rust/myserver/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-l" "avutil" "-l" "avcodec" "-l" "avdevice" "-l" "avformat" "-l" "avfilter" "-l" "avresample" "-l" "swresample" "-l" "swscale" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "rt" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: /usr/bin/ld: cannot find -lavresample
collect2: error: ld returned 1 exit status

My question is: is there a specific place where I have to put the ffmpeg libraries?

**Comment by meh** [comment]
Please see [here](https://github.com/meh/rust-ffmpeg-sys/issues/10).
